services:
  mysql:
    image: mysql:8
    container_name: challenge-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lightit-challenge
      MYSQL_USER: challenge_user
      MYSQL_PASSWORD: challenge
    ports:
      - "3306:3306"
    volumes:
      - challenge_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: challenge-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/lightit-challenge
      SPRING_DATASOURCE_USERNAME: challenge_user
      SPRING_DATASOURCE_PASSWORD: challenge
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  challenge_data:
