spring.application.name=challenge
spring.profiles.active=dev

springdoc.api-docs.path=/api-docs

springdoc.swagger-ui.path=/api-docs-ui
springdoc.packages-to-scan=com.lightit.challenge.controller
springdoc.pathsToMatch=/api/**