@startuml class_diagram

class User {
    - name: string
    - email: string
    - created_at: datetime
    - updated_at: datetime
    - address: Address
}
User --> Address

class Address {
    - street: string
    - number: string
    - city: string
    - state: string
    - country: string
}

class NotificationService {
    + send(user: User, data: Map<string, string>, notificationStrategy: string): void
    - getStrategy(NotificationStrategyEnum strategy): INotificationStrategy
}
NotificationService ..> INotificationStrategy
NotificationService ..> NotificationStrategyEnum

enum NotificationStrategyEnum {
    EMAIL
    SMS
}

interface INotificationStrategy {
    + send(user: User, data: Map<String, String>): void
}
INotificationStrategy <|-- EmailNotificationStrategy
INotificationStrategy <|-- SmsNotificationStrategy

class EmailNotificationStrategy {
    - adapter: IEmailNotificationService
    + send(user: User, data: Map<String, String>): void
}
EmailNotificationStrategy --> IEmailNotificationService

class JavaMailSenderAdapter {
    + send(email: string, subject: string, body: string): void
}
JavaMailSenderAdapter --|> IEmailNotificationService

interface IEmailNotificationService {
    + send(email: string, subject: string, body: string): void
}

class SmsNotificationStrategy {
    - adapter: SmsNotificationService
    + send(user: User, data: Map<string, string>): void
}
SmsNotificationStrategy --> SmsNotificationService

interface SmsNotificationService {
    + send(phoneNumber: string, message: string): void
}

class StorageService {
    - adapter: StorageAdapter
    + store(file: MultipartFile): string
}
StorageService --> StorageAdapter

interface StorageAdapter {
    + store(file: File): string
}

class CloudinaryAdapter {
    + store(file: File): string
}
CloudinaryAdapter --|> StorageAdapter


@enduml